name: Push Docker image with a deployed model backend app

on:
  [push]

env: 
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build_backend_docker_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      run: echo "Backend image"
      - name: Log into DockerHub
        run: |
          echo "Signing into DockerHub"
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          echo "Signed in successfully

      - name: Build Docker image
        run: | 
          echo "Building the image..."
          docker build -t jtomasz/returns-prediction-app:backend -f Dockerfile.backend .
          echo "Image build successfully"

      - name: Push Docker image to DockerHub
        run |
          echo "Pushing image do DockerHub"
          docker push jtomasz/returns-prediction-app:backend
          echo "Image pushed successfully"

